### ISSUE TITLE
Panic occured

### ISSUE THREAD

**Issue by itzmanish** [jiyeyuran/go-eventemitter#1]
eventemitter.go Line number 90

```golang 
defer func() {
	if r := recover(); r != nil {
		ee.logger.Error("SafeEmit() | event listener threw an error [event:%s]: %s", evt, r)
		debug.PrintStack()
	}
}()
```
This error is occuring everytime on changing producer state or start producing video/audio track in mediasoup go demo application.
How do I trace the actual error?

**Comment by jiyeyuran** [comment]
The panic stack should print the specific reason for the error, and the most likely reason is type mismatch. Check the latest demo application which should works for convertible type.

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jiyeyuran/go-eventemitter"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月6日(星期六) 凌晨1:15
收件人:&nbsp;"jiyeyuran/go-eventemitter"<go-eventemitter@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jiyeyuran/go-eventemitter] Panic occured (#1)





 
eventemitter.go Line number 90
 defer func() { 	if r := recover(); r != nil { 		ee.logger.Error("SafeEmit() | event listener threw an error [event:%s]: %s", evt, r) 		debug.PrintStack() 	} }()
 
This error is occuring everytime on changing producer state or start producing video/audio track in mediasoup go demo application.
 How do I trace the actual error?
